name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update version in manifest
        run: |
          sed -i 's/"version":\s*".*"/"version": "${{ steps.tag_version.outputs.new_version }}"/g' chrome/manifest.json
          sed -i 's/"version":\s*".*"/"version": "${{ steps.tag_version.outputs.new_version }}"/g' firefox/manifest.json
      - name: Zip Folder
        run: |
          zip -j -r chrome-${{ steps.tag_version.outputs.new_tag }}.zip chrome
          zip -j -r firefox-${{ steps.tag_version.outputs.new_tag }}.zip firefox
          cp chrome-${{ steps.tag_version.outputs.new_tag }}.zip chrome-latest.zip
          cp firefox-${{ steps.tag_version.outputs.new_tag }}.zip firefox-latest.zip
      - name: Sign Chrome Extension crx file
        uses: cardinalby/webext-buildtools-chrome-crx-action@2.0.3
        with:
          # zip file made at the packExtensionDir step
          zipFilePath: 'chrome-latest.zip'
          crxFilePath: 'chrome-${{ steps.tag_version.outputs.new_tag }}.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
          # The following is optional if you need update.xml file
          updateXmlPath: 'chrome_update.xml'
          updateXmlCodebaseUrl: 'https://github.com/wei032499/NYCU_Toolman/releases/download/${{ steps.tag_version.outputs.new_tag }}/chrome-${{ steps.tag_version.outputs.new_tag }}.crx'
      - name: Create firefox_update.json
        run: |
          echo '{"addons": {"{b898bf67-e0ae-41e9-aeb7-86630b67359c}": {"updates": [{"version": "${{ steps.tag_version.outputs.new_version }}", "update_link": "https://github.com/wei032499/NYCU_Toolman/releases/download/${{ steps.tag_version.outputs.new_tag }}/firefox-${{ steps.tag_version.outputs.new_tag }}.xpi"}]}}}' > firefox_update.json
      - name: Sign Firefox xpi file
        uses: cardinalby/webext-buildtools-firefox-sign-xpi-action@1.0.6
        with:
          zipFilePath: 'firefox-latest.zip'
          xpiFilePath: 'firefox-${{ steps.tag_version.outputs.new_tag }}.xpi'
          extensionId: '{b898bf67-e0ae-41e9-aeb7-86630b67359c}'
          channel: 'unlisted'
          timeoutMs: 600000
          jwtIssuer: ${{ secrets.FF_JWT_ISSUER }}
          jwtSecret: ${{ secrets.FF_JWT_SECRET }}
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          new_branch: 'latest'
          add: 'chrome-latest.zip firefox-latest.zip chrome_update.xml firefox_update.json'
          commit: '--force'
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: "chrome-${{ steps.tag_version.outputs.new_tag }}.zip,firefox-${{ steps.tag_version.outputs.new_tag }}.zip,chrome-${{ steps.tag_version.outputs.new_tag }}.crx,firefox-${{ steps.tag_version.outputs.new_tag }}.xpi"
