name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update version in manifest
        run: |
          sed -i 's/"version":\s*".*"/"version": "${{ steps.tag_version.outputs.new_version }}"/g' chrome/manifest.json
          sed -i 's/"version":\s*".*"/"version": "${{ steps.tag_version.outputs.new_version }}"/g' firefox/manifest.json
      - name: Zip Folder
        run: |
          zip -j -r chrome-${{ steps.tag_version.outputs.new_tag }}.zip chrome
          zip -j -r firefox-${{ steps.tag_version.outputs.new_tag }}.zip firefox
          cp chrome-${{ steps.tag_version.outputs.new_tag }}.zip chrome-latest.zip
          cp firefox-${{ steps.tag_version.outputs.new_tag }}.zip firefox-latest.zip
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: "chrome-${{ steps.tag_version.outputs.new_tag }}.zip,firefox-${{ steps.tag_version.outputs.new_tag }}.zip,chrome-latest.zip,firefox-latest.zip"